import React from "react";

export default function Retnetionai() {
  return (
    <main className="bg-gray-100 text-gray-800">
      <div class="max-w-3xl mx-auto p-6 bg-white shadow-md mt-10">
        <h1 class="text-3xl font-bold mb-4">Privacy Policy</h1>
        <p class="text-sm text-gray-500 mb-6">
          Last updated: November 24, 2024
        </p>

        <p class="mb-4">
          This Privacy Policy describes our policies and procedures on the
          collection, use, and disclosure of your information when you use
          RetentionAI and tells you about your privacy rights and how the law
          protects you.
        </p>

        <p class="mb-4">
          We use your data to provide and improve the Service. By using the
          Service, you agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <h2 class="text-2xl font-semibold mt-8 mb-4">
          Interpretation and Definitions
        </h2>

        <h3 class="text-xl font-semibold mt-6 mb-2">Interpretation</h3>
        <p class="mb-4">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions.
        </p>

        <h3 class="text-xl font-semibold mt-6 mb-2">Definitions</h3>
        <p class="mb-4">For the purposes of this Privacy Policy:</p>
        <ul class="list-disc list-inside mb-4 space-y-2">
          <li>
            <strong>Application</strong> refers to <strong>RetentionAI</strong>,
            the software program provided by the Company.
          </li>
          <li>
            <strong>Company</strong> (referred to as either "the Company", "We",
            "Us" or "Our" in this Agreement) refers to RetentionAI.
          </li>
          <li>
            <strong>Country</strong> refers to: United Kingdom
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone, or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Application.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself.
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service.
          </li>
        </ul>

        <h2 class="text-2xl font-semibold mt-8 mb-4">
          Collecting and Using Your Data
        </h2>

        <h3 class="text-xl font-semibold mt-6 mb-2">Types of Data Collected</h3>

        <h4 class="text-lg font-semibold mt-4 mb-2">Personal Data</h4>
        <p class="mb-4">
          While using our Service, we may collect certain device identifiers
          that are not linked to your identity. This includes:
        </p>
        <ul class="list-disc list-inside mb-4 space-y-2">
          <li>Device ID</li>
        </ul>
        <p class="mb-4">
          This data is collected to provide and improve the Service and is not
          linked to your personal identity.
        </p>

        <h4 class="text-lg font-semibold mt-4 mb-2">Usage Data</h4>
        <p class="mb-4">
          Usage Data is collected automatically when using the Service.
        </p>
        <p class="mb-4">
          Usage Data may include information such as your device's Internet
          Protocol address (e.g., IP address), device type, operating system
          version, the configuration of the app when utilizing our Service, the
          time and date of your use of the Service, and other diagnostic data.
        </p>

        <h4 class="text-lg font-semibold mt-4 mb-2">
          Data Collected by Third-Party Services
        </h4>
        <p class="mb-4">
          We use third-party services to monitor and analyze the use of our
          Service and to serve advertisements:
        </p>
        <ul class="list-disc list-inside mb-4 space-y-2">
          <li>
            <strong>Google AdMob:</strong> We use Google AdMob to serve ads
            within the Application. AdMob may collect information such as device
            type, operating system version, network provider, IP address, and
            app usage data. This information is collected to provide
            advertisements and analyze ad performance.{" "}
            <strong>We do not personalize ads.</strong> For more information on
            how Google collects and uses data, please visit{" "}
            <a
              href="https://policies.google.com/privacy"
              class="text-blue-600 hover:underline"
            >
              Google's Privacy Policy
            </a>{" "}
            and{" "}
            <a
              href="https://support.google.com/admob/answer/6128543"
              class="text-blue-600 hover:underline"
            >
              Google AdMob Policy
            </a>
            .
          </li>
          <li>
            <strong>PostHog:</strong> We use PostHog to collect anonymous usage
            analytics to help us improve the Service. This data is not linked to
            you personally and includes information such as feature usage and
            interaction patterns. For more information, please visit{" "}
            <a
              href="https://posthog.com/privacy"
              class="text-blue-600 hover:underline"
            >
              PostHog's Privacy Policy
            </a>
            .
          </li>
        </ul>

        <h3 class="text-xl font-semibold mt-6 mb-2">Use of Your Data</h3>
        <p class="mb-4">
          The Company may use the collected data for the following purposes:
        </p>
        <ul class="list-disc list-inside mb-4 space-y-2">
          <li>
            <strong>To provide and maintain our Service:</strong> Including to
            monitor the usage of our Service.
          </li>
          <li>
            <strong>To improve user experience:</strong> Analyzing usage
            patterns to enhance functionality and features.
          </li>
          <li>
            <strong>For advertising:</strong> Serving non-personalized
            advertisements through Google AdMob.
          </li>
          <li>
            <strong>For analytics:</strong> Using tools like PostHog to track
            user interactions and improve our Service.
          </li>
        </ul>

        <h3 class="text-xl font-semibold mt-6 mb-2">Retention of Your Data</h3>
        <p class="mb-4">
          We will retain Usage Data for internal analysis purposes. Usage Data
          is generally retained for a shorter period, except when this data is
          used to strengthen the security or to improve the functionality of our
          Service.
        </p>

        <h3 class="text-xl font-semibold mt-6 mb-2">Transfer of Your Data</h3>
        <p class="mb-4">
          Your information, including Usage Data, may be transferred to — and
          maintained on — computers located outside of your state, province,
          country, or other governmental jurisdiction where the data protection
          laws may differ from those of your jurisdiction.
        </p>
        <p class="mb-4">
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </p>

        <h3 class="text-xl font-semibold mt-6 mb-2">Disclosure of Your Data</h3>
        <p class="mb-4">
          We may disclose Usage Data in the following situations:
        </p>
        <ul class="list-disc list-inside mb-4 space-y-2">
          <li>
            <strong>With Service Providers:</strong> We may share Usage Data
            with third-party Service Providers to monitor and analyze the use of
            our Service.
          </li>
          <li>
            <strong>For legal requirements:</strong> If required to do so by law
            or in response to valid requests by public authorities.
          </li>
        </ul>

        <h3 class="text-xl font-semibold mt-6 mb-2">Security of Your Data</h3>
        <p class="mb-4">
          The security of your data is important to us. While we strive to use
          commercially acceptable means to protect your data, we cannot
          guarantee its absolute security.
        </p>

        <h2 class="text-2xl font-semibold mt-8 mb-4">Data Storage</h2>
        <p class="mb-4">
          All user data is stored locally on your device. We do not store any
          personal data on our servers.
        </p>

        <h2 class="text-2xl font-semibold mt-8 mb-4">Children's Privacy</h2>
        <p class="mb-4">
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personal data from anyone under the age of 13.
        </p>

        <h2 class="text-2xl font-semibold mt-8 mb-4">
          Links to Other Websites
        </h2>
        <p class="mb-4">
          Our Service may contain links to other websites that are not operated
          by us. We strongly advise you to review the Privacy Policy of every
          site you visit.
        </p>

        <h2 class="text-2xl font-semibold mt-8 mb-4">
          Changes to This Privacy Policy
        </h2>
        <p class="mb-4">
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p class="mb-4">
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>

        <h2 class="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
        <p class="mb-4">
          If you have any questions about this Privacy Policy, you can contact
          us:
        </p>
        <ul class="list-disc list-inside mb-4">
          <li>
            By email:{" "}
            <a
              href="mailto:hello@calebareeveso.com"
              class="text-blue-600 hover:underline"
            >
              hello@calebareeveso.com
            </a>
          </li>
        </ul>
      </div>
    </main>
  );
}
