import React from "react";

export default function Retnetionai() {
  return (
    <main className="bg-white text-gray-900">
      <div className="max-w-3xl mx-auto p-6">
        <h1 className="text-3xl font-bold mb-4">
          Privacy Policy For RetentionAI
        </h1>
        <p className="text-sm text-gray-600 mb-6">
          Last updated: November 25, 2024
        </p>

        <p className="mb-4">
          This Privacy Policy describes Our policies and procedures on the
          collection, use, and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>

        <p className="mb-4">
          We use Your Personal data to provide and improve the Service and to
          serve advertisements. By using the Service, You agree to the
          collection and use of information in accordance with this Privacy
          Policy.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          Interpretation and Definitions
        </h2>

        <h3 className="text-xl font-semibold mt-6 mb-2">Interpretation</h3>
        <p className="mb-4">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">Definitions</h3>
        <p className="mb-4">For the purposes of this Privacy Policy:</p>
        <ul className="list-disc list-inside mb-4 space-y-2">
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
          <li>
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by, or is under common control with a party, where
            "control" means ownership of 50% or more of the shares.
          </li>
          <li>
            <strong>Application</strong> refers to <strong>RetentionAI</strong>,
            the software program provided by the Company.
          </li>
          <li>
            <strong>Company</strong> (referred to as either "the Company", "We",
            "Us" or "Our" in this Agreement) refers to{" "}
            <strong>RetentionAI</strong>.
          </li>
          <li>
            <strong>Country</strong> refers to: United Kingdom
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone, or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Application.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself.
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          Collecting and Using Your Personal Data
        </h2>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          Types of Data Collected
        </h3>

        <h4 className="text-lg font-semibold mt-4 mb-2">Personal Data</h4>
        <p className="mb-4">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You.
        </p>

        <h4 className="text-lg font-semibold mt-4 mb-2">Usage Data</h4>
        <p className="mb-4">
          Usage Data is collected automatically when using the Service.
        </p>
        <p className="mb-4">
          Usage Data may include information such as Your Device's Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          unique device identifiers, and other diagnostic data.
        </p>
        <p className="mb-4">
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including but not limited
          to the type of mobile device You use, Your mobile device unique ID,
          Your mobile operating system, and other diagnostic data.
        </p>

        <h4 className="text-lg font-semibold mt-4 mb-2">
          Tracking Technologies and Cookies
        </h4>
        <p className="mb-4">
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. Tracking technologies
          used are beacons, tags, and scripts to collect and track information
          and to improve and analyze Our Service.
        </p>

        <h4 className="text-lg font-semibold mt-4 mb-2">Advertising</h4>
        <p className="mb-4">
          We may use Service Providers to show advertisements to You to help
          support and maintain Our Service.
        </p>

        <h5 className="text-base font-semibold mt-4 mb-2">Google AdMob</h5>
        <p className="mb-4">
          Google AdMob is an advertising service provided by Google Inc.
        </p>
        <p className="mb-4">
          Google AdMob may collect information such as device identifiers,
          location data, and other information as described in the Google
          Privacy Policy.
        </p>
        <p className="mb-4">
          You can opt-out from AdMob by following the instructions described by
          Google:{" "}
          <a
            href="https://adssettings.google.com/authenticated"
            className="text-blue-600 hover:underline"
          >
            Google Ad Settings
          </a>
        </p>
        <p className="mb-4">
          For more information on how Google uses the collected information,
          please visit the{" "}
          <a
            href="https://www.google.com/policies/privacy/"
            className="text-blue-600 hover:underline"
          >
            Google Privacy Policy
          </a>
          .
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          Use of Your Personal Data
        </h3>
        <p className="mb-4">
          The Company may use Personal Data for the following purposes:
        </p>
        <ul className="list-disc list-inside mb-4 space-y-2">
          <li>
            <strong>To provide and maintain our Service</strong>, including to
            monitor the usage of our Service.
          </li>
          <li>
            <strong>To manage Your Account</strong>: to manage Your registration
            as a user of the Service.
          </li>
          <li>
            <strong>For the performance of a contract</strong>: the development,
            compliance, and undertaking of the purchase contract for the
            products, items, or services You have purchased.
          </li>
          <li>
            <strong>To contact You</strong>: To contact You by email, telephone
            calls, SMS, or other equivalent forms of electronic communication.
          </li>
          <li>
            <strong>To provide You</strong> with news, special offers, and
            general information about other goods, services, and events.
          </li>
          <li>
            <strong>To manage Your requests</strong>: To attend and manage Your
            requests to Us.
          </li>
          <li>
            <strong>To provide personalized advertisements and content</strong>:
            We may use Your information to serve You with personalized
            advertisements, including using third-party advertising partners
            like Google AdMob.
          </li>
          <li>
            <strong>For business transfers</strong>: We may use Your information
            to evaluate or conduct a merger, divestiture, restructuring, or
            other sale of some or all of Our assets.
          </li>
          <li>
            <strong>For other purposes</strong>: We may use Your information for
            data analysis, identifying usage trends, and to improve our Service.
          </li>
        </ul>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          Sharing Your Personal Data
        </h3>
        <p className="mb-4">
          We may share Your personal information in the following situations:
        </p>
        <ul className="list-disc list-inside mb-4 space-y-2">
          <li>
            <strong>With Service Providers</strong>: We may share Your personal
            information with Service Providers to monitor and analyze the use of
            our Service.
          </li>
          <li>
            <strong>With Advertising Partners</strong>: We may share Your
            information with third-party advertising partners, such as Google
            AdMob, for delivering personalized advertisements to You.
          </li>
          <li>
            <strong>For business transfers</strong>: We may share or transfer
            Your personal information in connection with any merger or sale of
            Company assets.
          </li>
          <li>
            <strong>With Affiliates</strong>: We may share Your information with
            Our affiliates.
          </li>
          <li>
            <strong>With business partners</strong>: We may share Your
            information with Our business partners to offer You certain products
            or services.
          </li>
          <li>
            <strong>With other users</strong>: when You share personal
            information in public areas with other users.
          </li>
          <li>
            <strong>With Your consent</strong>: We may disclose Your personal
            information for any other purpose with Your consent.
          </li>
        </ul>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          Retention of Your Personal Data
        </h3>
        <p className="mb-4">
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          Transfer of Your Personal Data
        </h3>
        <p className="mb-4">
          Your information, including Personal Data, is processed at the
          Company's operating offices and in any other places where the parties
          involved are located.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          Delete Your Personal Data
        </h3>
        <p className="mb-4">
          You have the right to delete or request that We assist in deleting the
          Personal Data that We have collected about You.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          Disclosure of Your Personal Data
        </h3>
        <p className="mb-4">
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          Security of Your Personal Data
        </h3>
        <p className="mb-4">
          The security of Your Personal Data is important to Us, but no method
          of transmission over the Internet is 100% secure.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Children's Privacy</h2>
        <p className="mb-4">
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personal information from anyone under 13.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          Links to Other Websites
        </h2>
        <p className="mb-4">
          Our Service may contain links to other websites that are not operated
          by Us.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          Changes to this Privacy Policy
        </h2>
        <p className="mb-4">
          We may update Our Privacy Policy from time to time.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
        <p className="mb-4">
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>
        <ul className="list-disc list-inside mb-4 space-y-2">
          <li>
            By email:{" "}
            <a
              href="mailto:hello@calebareeveso.com"
              className="text-blue-600 hover:underline"
            >
              hello@calebareeveso.com
            </a>
          </li>
        </ul>
      </div>
    </main>
  );
}
